name: Common
description: Common setup

runs:
  using: "composite"
  steps:
    - name: Cache turborepo
      uses: actions/cache@v4
      with:
        path: .turbo
        key: ${{ runner.os }}-turbo-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-turbo-

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: "21"
        cache: "yarn"

    - name: Install dependencies
      shell: bash
      run: yarn
