name: 🚀 Deploy Production
on:
  push:
    branches:
      - production
jobs:
  ci:
    uses: ./.github/workflows/ci.yml

  cdk-production:
    name: CDK
    uses: ./.github/workflows/publish.yml
    needs: ci
    with:
      workspace_name: cdk
      service_name: morph-cdk-production
      version: patch
    secrets: inherit
