name: 🚅 Deploy Staging
on:
  push:
    branches:
      - main
jobs:
  ci:
    uses: ./.github/workflows/ci.yml

  cdk-staging:
    name: CDK
    uses: ./.github/workflows/publish.yml
    needs: ci
    with:
      workspace_name: cdk
      service_name: runmorph-cdk-staging
      version: patch
    secrets: inherit
